### ISSUE TITLE
MIL on cat/dog dataset

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [Dipeshtamboli/Image-Classification-and-Localization-using-Multiple-Instance-Learning#1]
Hi Dipesh,
I am trying to run A-MIL code on Cat and Dog images, with 300, 900 training images respectively. The images are of size 362x428.
But I am observing that the Test Accuracy is constant at 62.79 percent after 2 epochs. Test accuracy is not varying at all. The training accuracy is varying but not increasing beyond 68 percent. I have run around 10 epochs. 
What worries me is, the constant Test Accuracy. 
Does your code has some data distribution requirement. Do you think there should be any changes in the data or somewhere in the code, to make this work on Cat and Dog images.
Is there anything which is data specific (exclusively written for BACH and BreakHIS datasets)
Your help would be appreciated.
Regards

**Comment by Dipeshtamboli** [comment]
Hello Ajaz,
As sub-parts of your image(only leg/tail/abdomen) don't directly correspond to any class, it may be possible that the A-MIL method will not work for you. As the tissue images or BACH and BreakHIS data consist of multiple tissues/nucleus/cells in one image, their sub-parts can also be count as one unit and thus forms a meaningful entity, unlike the natural objects.
