### ISSUE TITLE
BreakHis image classifier

### ISSUE THREAD

**Issue by bplm** [Dipeshtamboli/Image-Classification-and-Localization-using-Multiple-Instance-Learning#2]
Respected Sir,
I am working on attention in image classification on the same dataset Breakhis. I had few queries..
I was implementing Linformer as vision Transformer ...but after training my model , When i run it on test set and check for predicted lables,I find that all of them are labelled as 0(benign)..further when i check targets in the test set ..all show up to be same..pls help sir!!

**Comment by Dipeshtamboli** [comment]
Hello,
I think you are not using this A-MIL method for the classification and localization but Linformer as a vision Transformer. Sorry but I don't have any idea of that. Further, it seems like all your output is collapsing to class zero. There can be many problems. You can start by checking your evaluation code if it is labelling correctly or not.
As your doubt/issue is not related to this specific project, I am closing this issue.
