### ISSUE TITLE
How can I extend this to a bigger network or a multi-class problem?

### ISSUE THREAD

**Issue by PyJulie** [Dipeshtamboli/Image-Classification-and-Localization-using-Multiple-Instance-Learning#4]
Can I directly change the feature extractors to the VGG or Resnet?
From my point of view, the MIL pooling layer can not aggregate the information of all patches and make a decision based on the global features? For example, if I change the Sigmoid function to Softmax and evaluate the MIL on the MNIST, it will not work since the part of number may  correspond to multiple classes?

**Comment by Dipeshtamboli** [comment]
Yes, you can change the feature extractors to any architecture you prefer.
This whole Classification and Localization using MIL works on the images where the content distribution of any part of the image matches with the distribution of the complete image. i.e., the images where you can find repetitive structure(Some design, cell/tissue structure, etc.). Also, it will not work on the images where an object is present, and the parts of the objects are dissimilar(like a dog having a head different from the legs or tail). 
Yes, you are correct. It will neither work on the MNIST as well.
